# model
model_name_or_path: 'facebook/opt-350m'
cache_dir: '/remote-home/share/llms'
# data
refresh: false
data_tag: 'dummy_data'
train_on_inputs: false
max_length: 32
# tunelite
output_dir: './output'
do_eval: true
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 0.0005
num_train_epochs: 3
log_level: 'info'
logging_steps: 5
save_strategy: 'epoch'
seed: 42
run_name: 'example_tensor'
remove_unused_columns: false
metric_for_best_model: 'my_metric'
greater_is_better: true
eval_steps: 10
report_to: 'wandb'
deepspeed: 'ds_config.json'
#seq2seqtraining
predict_with_generate: true
generation_max_length: 400
generation_num_beams: 1
max_new_tokens: 100
temperature: 1.0
top_p: 1.0